export interface TeamMember {
  name: string;
  id: number;
  tasks: string | [];
  lastSeen: string;
  avatar?: string;
  role?: string;
  rating?: number;
  status?: string;
  email?: string;
  slack?: string;
  skills?: string[];
  specialties?: string[];
  tasksCompleted?: number;
  monthlyKPI?: number;
  topSkills?: { name: string; rating: number; color: string }[];
}

// export const teamMembers: TeamMember[] = [
//   {
//     name: 'Jacob Jones',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent.jpg',
//     role: 'Product Designer',
//     rating: 4.3,
//     status: 'Available',
//     email: 'jacobjones@company.com',
//     slack: 'jacobjones@company.com',
//     skills: ['Node.js', 'Python', 'PostgreSQL'],
//     specialties: ['API Design', 'Database Optimization', 'System Architecture'],
//     tasksCompleted: 123,
//     monthlyKPI: 67,
//     topSkills: [
//       { name: 'React', rating: 70, color: 'bg-purple-500' },
//       { name: 'Python', rating: 70, color: 'bg-blue-500' },
//       { name: 'Typescript', rating: 70, color: 'bg-orange-500' },
//     ],
//   },
//   {
//     name: 'Ronald Richards',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent1.jpg',
//     role: 'Backend Developer',
//     rating: 4.5,
//     status: 'Available',
//     email: 'ronaldrichards@company.com',
//     slack: 'ronaldrichards@company.com',
//     skills: ['Node.js', 'MongoDB', 'Express', 'Docker'],
//     specialties: ['Microservices', 'API Development', 'DevOps'],
//     tasksCompleted: 98,
//     monthlyKPI: 72,
//     topSkills: [
//       { name: 'Node.js', rating: 85, color: 'bg-green-500' },
//       { name: 'MongoDB', rating: 78, color: 'bg-blue-500' },
//       { name: 'Docker', rating: 82, color: 'bg-indigo-500' },
//     ],
//   },
//   {
//     name: 'Darrell Steward',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent2.jpg',
//     role: 'Product Manager',
//     rating: 4.7,
//     status: 'Busy',
//     email: 'darrellsteward@company.com',
//     slack: 'darrellsteward@company.com',
//     skills: ['Agile', 'Scrum', 'Jira', 'Leadership'],
//     specialties: [
//       'Product Strategy',
//       'Team Management',
//       'Stakeholder Communication',
//     ],
//     tasksCompleted: 145,
//     monthlyKPI: 89,
//     topSkills: [
//       { name: 'Leadership', rating: 90, color: 'bg-yellow-500' },
//       { name: 'Agile', rating: 85, color: 'bg-red-500' },
//       { name: 'Strategy', rating: 88, color: 'bg-pink-500' },
//     ],
//   },
//   {
//     name: 'Cameron Williamson',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent4.jpg',
//     role: 'Full Stack Developer',
//     rating: 4.4,
//     status: 'Available',
//     email: 'cameronwilliamson@company.com',
//     slack: 'cameronwilliamson@company.com',
//     skills: ['React', 'Node.js', 'TypeScript', 'AWS'],
//     specialties: [
//       'Full Stack Development',
//       'Cloud Architecture',
//       'Performance Optimization',
//     ],
//     tasksCompleted: 110,
//     monthlyKPI: 75,
//     topSkills: [
//       { name: 'React', rating: 88, color: 'bg-blue-500' },
//       { name: 'TypeScript', rating: 82, color: 'bg-blue-600' },
//       { name: 'AWS', rating: 79, color: 'bg-orange-500' },
//     ],
//   },
//   {
//     name: 'Bessie Cooper',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent3.jpg',
//     role: 'UI/UX Designer',
//     rating: 4.6,
//     status: 'Available',
//     email: 'bessiecooper@company.com',
//     slack: 'bessiecooper@company.com',
//     skills: ['Figma', 'Sketch', 'Adobe XD', 'Prototyping'],
//     specialties: ['User Research', 'Design Systems', 'Wireframing'],
//     tasksCompleted: 87,
//     monthlyKPI: 71,
//     topSkills: [
//       { name: 'Figma', rating: 92, color: 'bg-purple-500' },
//       { name: 'UI/UX', rating: 88, color: 'bg-indigo-500' },
//       { name: 'Prototyping', rating: 85, color: 'bg-pink-500' },
//     ],
//   },
//   {
//     name: 'Ralph Edwards',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent5.jpg',
//     role: 'Frontend Developer',
//     rating: 4.2,
//     status: 'Available',
//     email: 'ralphedwards@company.com',
//     slack: 'ralphedwards@company.com',
//     skills: ['React', 'Vue.js', 'CSS', 'JavaScript'],
//     specialties: ['Responsive Design', 'Component Libraries', 'Animation'],
//     tasksCompleted: 102,
//     monthlyKPI: 68,
//     topSkills: [
//       { name: 'React', rating: 80, color: 'bg-blue-500' },
//       { name: 'Vue.js', rating: 75, color: 'bg-green-500' },
//       { name: 'CSS', rating: 85, color: 'bg-pink-500' },
//     ],
//   },
//   {
//     name: 'Marvin McKinney',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent6.jpg',
//     role: 'QA Tester',
//     rating: 4.8,
//     status: 'Available',
//     email: 'marvinmckinney@company.com',
//     slack: 'marvinmckinney@company.com',
//     skills: ['Selenium', 'Jest', 'Cypress', 'Postman'],
//     specialties: ['Test Automation', 'Bug Tracking', 'Performance Testing'],
//     tasksCompleted: 156,
//     monthlyKPI: 82,
//     topSkills: [
//       { name: 'Selenium', rating: 87, color: 'bg-green-500' },
//       { name: 'Jest', rating: 80, color: 'bg-red-500' },
//       { name: 'Cypress', rating: 83, color: 'bg-teal-500' },
//     ],
//   },
//   {
//     name: 'Jerome Bell',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent7.jpg',
//     role: 'DevOps Engineer',
//     rating: 4.5,
//     status: 'Busy',
//     email: 'jeromebell@company.com',
//     slack: 'jeromebell@company.com',
//     skills: ['Docker', 'Kubernetes', 'CI/CD', 'AWS'],
//     specialties: ['Infrastructure', 'Automation', 'Cloud Services'],
//     tasksCompleted: 134,
//     monthlyKPI: 78,
//     topSkills: [
//       { name: 'Docker', rating: 90, color: 'bg-blue-500' },
//       { name: 'Kubernetes', rating: 85, color: 'bg-indigo-500' },
//       { name: 'AWS', rating: 88, color: 'bg-orange-500' },
//     ],
//   },
//   {
//     name: 'Guy Hawkins',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent8.jpg',
//     role: 'Graphic Designer',
//     rating: 4.3,
//     status: 'Available',
//     email: 'guyhawkins@company.com',
//     slack: 'guyhawkins@company.com',
//     skills: ['Photoshop', 'Illustrator', 'InDesign', 'Branding'],
//     specialties: ['Brand Identity', 'Visual Design', 'Print Design'],
//     tasksCompleted: 95,
//     monthlyKPI: 70,
//     topSkills: [
//       { name: 'Photoshop', rating: 92, color: 'bg-purple-500' },
//       { name: 'Illustrator', rating: 88, color: 'bg-orange-500' },
//       { name: 'Branding', rating: 85, color: 'bg-pink-500' },
//     ],
//   },
//   {
//     name: 'Savannah Nguyen',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent9.jpg',
//     role: 'Mobile Developer',
//     rating: 4.6,
//     status: 'Available',
//     email: 'savannahnguyen@company.com',
//     slack: 'savannahnguyen@company.com',
//     skills: ['React Native', 'Swift', 'Kotlin', 'Flutter'],
//     specialties: [
//       'iOS Development',
//       'Android Development',
//       'Cross-platform Apps',
//     ],
//     tasksCompleted: 118,
//     monthlyKPI: 76,
//     topSkills: [
//       { name: 'React Native', rating: 86, color: 'bg-blue-500' },
//       { name: 'Swift', rating: 82, color: 'bg-orange-500' },
//       { name: 'Kotlin', rating: 80, color: 'bg-purple-500' },
//     ],
//   },
//   {
//     name: 'Leslie Alexander',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/lady.jpg',
//     role: 'Frontend Developer',
//     rating: 4.4,
//     status: 'Available',
//     email: 'lesliealexander@company.com',
//     slack: 'lesliealexander@company.com',
//     skills: ['React', 'TypeScript', 'CSS', 'Tailwind'],
//     specialties: [
//       'UI Development',
//       'Performance Optimization',
//       'Accessibility',
//     ],
//     tasksCompleted: 112,
//     monthlyKPI: 78,
//     topSkills: [
//       { name: 'React', rating: 88, color: 'bg-blue-500' },
//       { name: 'TypeScript', rating: 82, color: 'bg-blue-600' },
//       { name: 'CSS', rating: 85, color: 'bg-pink-500' },
//     ],
//   },
//   {
//     name: 'Floyd Miles',
//     tasks: '12 active tasks',
//     lastSeen: '12:12',
//     avatar: '/images/gent4.jpg',
//     role: 'Content Writer',
//     rating: 4.8,
//     status: 'Available',
//     email: 'floydmiles@company.com',
//     slack: 'floydmiles@company.com',
//     skills: ['Copywriting', 'SEO', 'Content Strategy', 'Research'],
//     specialties: ['Technical Writing', 'Content Strategy', 'Blog Writing'],
//     tasksCompleted: 201,
//     monthlyKPI: 94,
//     topSkills: [
//       { name: 'Copywriting', rating: 95, color: 'bg-orange-500' },
//       { name: 'SEO', rating: 88, color: 'bg-green-500' },
//       { name: 'Research', rating: 90, color: 'bg-blue-500' },
//     ],
//   },
// ];
