import type { Task, Column } from "@/components/types";

export const COLUMNS: Column[] = [
  {
    id: "BACKLOG",
    title: "Backlog",
    subTitle: "You can drag task to any category",
    taskCount: 5,
    textColor: "text-[#CA8A04]",
    bgColor: "bg-[#EAB3081A]",
  },
  {
    id: "TODO",
    title: "To Do",
    subTitle: "You can drag task to any category",
    taskCount: 3,
    textColor: "text-[#DB2777]",
    bgColor: "bg-[#EC48991A]",
  },
  {
    id: "IN_PROGRESS",
    title: "In Progress",
    subTitle: "You can drag task to any category",
    taskCount: 2,
    textColor: "text-[#9333EA]",
    bgColor: "bg-[#A855F71A]",
  },
  {
    id: "DONE",
    title: "Done",
    subTitle: "You can drag task to any category",
    taskCount: 5,
    textColor: "text-[#16A34A]",
    bgColor: "bg-[#22C55E1A]",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "1",
    title: "Modle Answer",
    description: "Gather requirements and create initial documentation",
    status: "BACKLOG",
    statusColor: "bg-yellow-100 text-yellow-700",
    taskId: "#UI007",
    taskIdColor: "bg-blue-100 text-blue-700",
    category: "Design",
    categoryColor: "bg-green-100 text-green-700",
    priority: "High",
    files: 4,
    fileColor: "text-[#17A5E6]",
    attachments: 2,
    attachmentColor: "text-[#c000f7]",
    messages: 3,
    messageColor: "text-[#f59e22]",
    messageBackground: "#f59e22",
    avatars: [
    { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
    { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
    { fallback: "+5" } // no image, fallback only
  ]
  },
  {
    id: "2",
    title: "Create calendar, chat and email app pages",
    description: "Gather requirements and create initial documentation",
    status: "BACKLOG",
    statusColor: "bg-yellow-100 text-yellow-700",
    taskId: "#UI003",
    taskIdColor: "bg-blue-100 text-blue-700",
    category: "Development",
    categoryColor: "bg-green-100 text-green-700",
    priority: "High",
    files: 1,
    fileColor: "text-[#17A5E6]",
    fileBackground: "#17A5E6",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#DADEE5",
    messages: 3,
    messageColor: "text-[#939393]",
    messageBackground: "#DADEE5",
    avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
]

  },
  {
    id: "3",
    title: "Product Design, Figma, Sketch (Software), Prototype",
    description: "Gather requirements and create initial documentation",
    status: "BACKLOG",
    statusColor: "bg-yellow-100 text-yellow-700",
    taskId: "#BC05",
    taskIdColor: "bg-blue-100 text-blue-700",
    category: "Project",
    categoryColor: "bg-green-100 text-green-700",
    priority: "High",
    files: 2,
    fileColor: "text-[#939393]",
    fileBackground: "#DADEE5",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#DADEE5",
    messages: 3,
    messageColor: "text-[#939393]",
    messageBackground: "#DADEE5",
 avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
]

  },
  {
    id: "4",
    title: "Change email option process",
    description: "Gather requirements and create initial documentation",
    status: "BACKLOG",
    statusColor: "bg-yellow-100 text-yellow-700",
    taskId: "#FTC07",
    taskIdColor: "bg-blue-100 text-blue-700",
    category: "Project",
    categoryColor: "bg-green-100 text-green-700",
    priority: "High",
    files: 2,
    fileColor: "text-[#939393]",
    fileBackground: "#DADEE5",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#DADEE5",
    messages: 3,
    messageColor: "text-[#939393]",
    messageBackground: "#DADEE5",
     avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
  {
    id: "5",
    title: "Model Answer",
    description: "Create component library and design tokens",
    status: "TODO",
    statusColor: "bg-[#EC48991A] text-[#DB2777]",
    taskId: "#UI005",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    messages: 4,
    messageColor: "text-[#939393]",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },

  {
    id: "6",
    title: "Add authentication pages",
    description: "Create component library and design tokens",
    status: "TODO",
    statusColor: "bg-[#EC48991A] text-[#DB2777]",
    taskId: "##UI008",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    messages: 4,
    messageColor: "text-[#939393]",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
  {
    id: "7",
    title: "Model Answer",
    description: "Implement REST API endpoints",
    status: "IN_PROGRESS",
    statusColor: "bg-[#A855F71A] text-[#9333EA]",
    taskId: "#002",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    fileBackground: "#5B80A7",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#5B80A7",
    messages: 4,
    messageColor: "text-[#939393]",
    messageBackground: "#5B80A7",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
  {
    id: "8",
    title: "Model Answer",
    description: "Implement REST API endpoints",
    status: "IN_PROGRESS",
    statusColor: "bg-[#A855F71A] text-[#9333EA]",
    taskId: "#002",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    fileBackground: "#5B80A7",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#5B80A7",
    messages: 4,
    messageColor: "text-[#939393]",
    messageBackground: "#5B80A7",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
  {
    id: "9",
    title: "Model Answer",
    description: "Write unit tests for core functionality",
    status: "DONE",
    statusColor: "bg-[#22C55E1A] text-[#16A34A]",
    taskId: "#UI005",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    fileBackground: "#DADEE5",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#DADEE5",
    messages: 4,
    messageColor: "text-[#939393]",
    messageBackground: "#DADEE5",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
  {
    id: "10",
    title: "Create calendar, chat and email app pages",
    description: "Write unit tests for core functionality",
    status: "DONE",
    statusColor: "bg-[#22C55E1A] text-[#16A34A]",
    taskId: "#UI005",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    fileBackground: "#DADEE5",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#DADEE5",
    messages: 4,
    messageColor: "text-[#939393]",
    messageBackground: "#DADEE5",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
  {
    id: "11",
    title: "Product Design, Figma, Sketch (Software), Prototype",
    description: "Write unit tests for core functionality",
    status: "DONE",
    statusColor: "bg-[#22C55E1A] text-[#16A34A]",
    taskId: "#UI005",
    taskIdColor: "bg-[#EBEEF2] text-[#626262]",
    priority: "High",
    files: 1,
    fileColor: "text-[#939393]",
    fileBackground: "#DADEE5",
    attachments: 2,
    attachmentColor: "text-[#939393]",
    attahmentBackground: "#DADEE5",
    messages: 4,
    messageColor: "text-[#939393]",
    messageBackground: "#DADEE5",
         avatars: [
  { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "User 1", fallback: "U1" },
  { src: "https://randomuser.me/api/portraits/women/44.jpg", alt: "User 2", fallback: "U2" },
  { fallback: "+5" }
     ]
  },
];
